// constant
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM

// 数据获取，一般不直接和reducer交互
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED'
export type USER_FETCH_REQUESTED = typeof USER_FETCH_REQUESTED
// 数据获取成功
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED'
export type USER_FETCH_SUCCEEDED = typeof USER_FETCH_SUCCEEDED
// 获取失败
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'
export type USER_FETCH_FAILED = typeof USER_FETCH_FAILED
