// constant
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export type USER_FETCH_REQUESTED = typeof USER_FETCH_REQUESTED;


export const INIT_LIST_ACTION = 'INIT_LIST_ACTION';
export type INIT_LIST_ACTION = typeof INIT_LIST_ACTION;

export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export type USER_FETCH_SUCCEEDED = typeof USER_FETCH_SUCCEEDED;

export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export type USER_FETCH_FAILED = typeof USER_FETCH_FAILED;
